---
title: "EY114 Analysis"
author: "Emily Yang"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(readxl)
library(ggplot2)
library(ggpubr)
library(DescTools)

df <- read_excel("~/Documents/Experiments/5.27.26 EY114 CantonS.xlsx", 
    sheet = "Sheet1")
```

```{r}
newdf<- df %>%
  group_by(ID) %>%
  summarize(across(A1:G11, max)) 


min <-c(0,4.5,9,13.5,18,22.5,27,31.5,36,40.5,45,49.5,54,58.5,63,67.5,72,76.5,81,85.5,90,94.5,99,103.5,108,112.5,117,121.5,126,130.5,135,139.5,144,148.5,153,157.5,162,166.5,171,175.5,180,184.5,189,193.5,198,202.5,207,211.5,216,220.5,225,229.5,234,238.5,243,247.5,252,256.5,261,265.5,270,274.5,279,283.5,288,292.5,297,301.5,306,310.5,315,319.5,324,328.5,333,337.5,342,346.5,351,355.5,360,364.5,369,373.5,378,382.5,387,391.5,396,400.5,405,409.5,414,418.5,423,427.5,432,436.5,441,445.5,450,454.5,459,463.5,468,472.5,477,481.5,486,490.5,495,499.5,504,508.5,513,517.5,522,526.5,531,535.5,540,544.5,549,553.5,558,562.5,567,571.5,576,580.5,585,589.5,594,598.5,603,607.5,612,616.5,621,625.5,630,634.5,639,643.5,648,652.5,657,661.5,666,670.5,675,679.5,684,688.5,693,697.5,702,706.5,711,715.5,720,724.5,729,733.5,738,742.5,747,751.5,756,760.5,765,769.5,774,778.5,783,787.5,792,796.5,801,805.5,810,814.5,819,823.5,828,832.5,837,841.5,846,850.5,855,859.5,864,868.5,873,877.5,882,886.5,891,895.5,900,904.5,909,913.5,918,922.5,927,931.5,936,940.5,945,949.5,954,958.5,963,967.5,972,976.5,981,985.5,990,994.5,999,1003.5,1008,1012.5,1017,1021.5,1026,1030.5,1035,1039.5,1044,1048.5,1053,1057.5,1062,1066.5,1071,1075.5,1080,1084.5,1089,1093.5,1098,1102.5,1107,1111.5,1116,1120.5,1125) 

i <- cbind(newdf,min)
```

```{r Lum}
colors <- c("Alive" = "steelblue", "Control" = "black", "Dead" = "red", "Delayed Dead"="purple")

p <- ggplot(i, aes(x=min)) + 
  geom_line(aes(y = A1, color="Delayed Dead")) + 
  geom_line(aes(y = A3, color="Delayed Dead")) + 
  #geom_line(aes(y = A5, color="Alive")) + 
  #geom_line(aes(y = A7, color="Alive")) + 
  geom_line(aes(y = A9, color="Delayed Dead")) + 
  geom_line(aes(y = A11, color="Control")) + 
  geom_line(aes(y = C1, color="Delayed Dead")) + 
  geom_line(aes(y = C3, color="Delayed Dead")) + 
  #geom_line(aes(y = C5, color="Alive")) + 
  geom_line(aes(y = C7, color="Delayed Dead")) + 
  #geom_line(aes(y = C9, color="Alive")) + 
  geom_line(aes(y = C11, color="Control")) +
  geom_line(aes(y = E1, color="Delayed Dead")) + 
  geom_line(aes(y = E3, color="Delayed Dead")) +
  geom_line(aes(y = E5, color="Delayed Dead")) + 
  geom_line(aes(y = E7, color="Delayed Dead")) + 
  geom_line(aes(y = E9, color="Dead")) +
  geom_line(aes(y = E11, color="Control")) +
  geom_line(aes(y = G1, color="Delayed Dead")) + 
  geom_line(aes(y = G3, color="Dead")) + 
  geom_line(aes(y = G5, color="Delayed Dead")) + 
  #geom_line(aes(y = G7, color="Alive")) + 
  geom_line(aes(y = G9, color="Delayed Dead")) + 
  geom_line(aes(y = G11, color="Control")) + 
  labs(title="EY114 Dead",
        x ="Time (min)", y = "Luminescence (AU)", color = "Legend")+
    scale_color_manual(values = colors)+
  ylim(0,15000)
p
#ggsave("EY114 Dead.png")

p <- ggplot(i, aes(x=min)) + 
  geom_line(aes(y = E9, color="Dead")) + 
  geom_vline(xintercept = 306, color = "black")+
  labs(title="EY114 G3 Dead",
        x ="Time (min)", y = "Luminescence (AU)", color = "Legend")+
    scale_color_manual(values = colors)
p
#ggsave("EY114 E9.png")

```

```{r}
my_vec <- numeric()

for (col in i) {
    a <- AUC(min, col, method = c("trapezoid"))
    my_vec <- c(my_vec, a)
}

print(my_vec)
```

```{r AUC}
df <- data.frame(dose=c("Delayed Dead","Delayed Dead","Alive","Alive","Delayed Dead","Control","Delayed Dead","Delayed Dead","Alive","Delayed Dead","Alive","Control","Delayed Dead","Delayed Dead","Delayed Dead","Delayed Dead","Dead","Control","Delayed Dead","Dead","Delayed Dead","Alive","Delayed Dead","Control"),
    len=c(3654306.00, 2233372.50, 2260707.75, 1623809.25, 2981911.50,   13689.00, 3372945.75, 2655450.00, 1738631.25, 2359633.50, 1883610.00,   13938.75, 3363068.25, 3170074.50, 2963895.75, 1961480.25, 2454810.75,  14001.75, 2771574.75,  328473.00, 2883930.75, 1462734.00, 2848023.00,   13461.75))

    
my_comparisons <- list(c("Alive", "Dead"), c("Dead", "Delayed Dead"), c("Alive", "Delayed Dead"),c("Alive", "Control"))

p <- ggplot(df, aes(x=dose, y=len)) +
geom_bar(stat="summary", 
           fun=mean,
           aes(fill=dose)) +
  geom_point(position = position_jitter(width = 0.2), color = "black")+
  stat_compare_means(comparisons = my_comparisons)+
  scale_fill_manual(values = c("#00BFC4","#7CAE00", "#F8766D","#C77CFF"))+
  labs(title="EY114 Lum AUC",
        x ="Condition", y = "Area Under Curve")
p


#ggsave("EY114 LAUC.png")
```
```{r Subset}

j <- subset(i, min <= 1039.5)
min <-c(0,4.5,9,13.5,18,22.5,27,31.5,36,40.5,45,49.5,54,58.5,63,67.5,72,76.5,81,85.5,90,94.5,99,103.5,108,112.5,117,121.5,126,130.5,135,139.5,144,148.5,153,157.5,162,166.5,171,175.5,180,184.5,189,193.5,198,202.5,207,211.5,216,220.5,225,229.5,234,238.5,243,247.5,252,256.5,261,265.5,270,274.5,279,283.5,288,292.5,297,301.5,306,310.5,315,319.5,324,328.5,333,337.5,342,346.5,351,355.5,360,364.5,369,373.5,378,382.5,387,391.5,396,400.5,405,409.5,414,418.5,423,427.5,432,436.5,441,445.5,450,454.5,459,463.5,468,472.5,477,481.5,486,490.5,495,499.5,504,508.5,513,517.5,522,526.5,531,535.5,540,544.5,549,553.5,558,562.5,567,571.5,576,580.5,585,589.5,594,598.5,603,607.5,612,616.5,621,625.5,630,634.5,639,643.5,648,652.5,657,661.5,666,670.5,675,679.5,684,688.5,693,697.5,702,706.5,711,715.5,720,724.5,729,733.5,738,742.5,747,751.5,756,760.5,765,769.5,774,778.5,783,787.5,792,796.5,801,805.5,810,814.5,819,823.5,828,832.5,837,841.5,846,850.5,855,859.5,864,868.5,873,877.5,882,886.5,891,895.5,900,904.5,909,913.5,918,922.5,927,931.5,936,940.5,945,949.5,954,958.5,963,967.5,972,976.5,981,985.5,990,994.5,999,1003.5,1008,1012.5,1017,1021.5,1026,1030.5,1035,1039.5) 

my_vec <- numeric()

for (col in j) {
    a <- AUC(min, col, method = c("trapezoid"))
    my_vec <- c(my_vec, a)
}

print(my_vec)
```


```{r Location, include=FALSE}

ddf1<- df %>%
pivot_longer(cols=setdiff(colnames(df), c("ID", "Position")), names_to = "Fly", values_to ="Brightness")

newddf1 <- ddf1 %>%
  group_by(ID, Fly) %>%
  summarize(max_bright = max(Brightness)) %>%
  ungroup()
newddf1

output <- tibble(Fly=NULL, ID = NULL, Position = NULL)
for (k in c(1:nrow(ddf1))) {
  lab <- ddf1$ID[k] 
  fly <- ddf1$Fly[k]
  pos <- ddf1$Position[k] 
  brightness <- ddf1$Brightness[k]
  max_value <- filter(newddf1, ID == lab & Fly == fly) %>%
    select(max_bright) %>% pull()
  if (max_value == brightness) {
    output <- bind_rows(output, tibble(Fly=fly, ID = lab, Position = pos))
  }
}


output1<- output %>%
pivot_wider(id_cols = ID, names_from = Fly, values_from = Position)
output1

```